packages:
  - "packages/*"
  - "apps/*"
  - "tools/*"

minimumReleaseAgeExclude:
  - "@cloudflare/kumo@2.9.2"

allowBuilds:
  "@parcel/watcher": true
  core-js-pure: true
  esbuild: true
  msgpackr-extract: true
  workerd: true

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.7
  vitest: 4.1.10
