/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as ReplaysRouteImport } from './routes/replays'
import { Route as SimulationsRouteImport } from './routes/simulations'
import { Route as SystemRouteImport } from './routes/system'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as SettingsAccessRouteImport } from './routes/settings/access'
import { Route as SettingsProvidersRouteImport } from './routes/settings/providers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplaysRoute = ReplaysRouteImport.update({
  id: '/replays',
  path: '/replays',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsRoute = SimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccessRoute = SettingsAccessRouteImport.update({
  id: '/settings/access',
  path: '/settings/access',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/settings/providers',
  path: '/settings/providers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRoute
  '/models': typeof ModelsRoute
  '/replays': typeof ReplaysRoute
  '/simulations': typeof SimulationsRoute
  '/system': typeof SystemRoute
  '/usage': typeof UsageRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/settings/access': typeof SettingsAccessRoute
  '/settings/providers': typeof SettingsProvidersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRoute
  '/models': typeof ModelsRoute
  '/replays': typeof ReplaysRoute
  '/simulations': typeof SimulationsRoute
  '/system': typeof SystemRoute
  '/usage': typeof UsageRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/settings/access': typeof SettingsAccessRoute
  '/settings/providers': typeof SettingsProvidersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRoute
  '/models': typeof ModelsRoute
  '/replays': typeof ReplaysRoute
  '/simulations': typeof SimulationsRoute
  '/system': typeof SystemRoute
  '/usage': typeof UsageRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/settings/access': typeof SettingsAccessRoute
  '/settings/providers': typeof SettingsProvidersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/decisions'
    | '/models'
    | '/replays'
    | '/simulations'
    | '/system'
    | '/usage'
    | '/sessions/$sessionId'
    | '/settings/access'
    | '/settings/providers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/decisions'
    | '/models'
    | '/replays'
    | '/simulations'
    | '/system'
    | '/usage'
    | '/sessions/$sessionId'
    | '/settings/access'
    | '/settings/providers'
  id:
    | '__root__'
    | '/'
    | '/decisions'
    | '/models'
    | '/replays'
    | '/simulations'
    | '/system'
    | '/usage'
    | '/sessions/$sessionId'
    | '/settings/access'
    | '/settings/providers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecisionsRoute: typeof DecisionsRoute
  ModelsRoute: typeof ModelsRoute
  ReplaysRoute: typeof ReplaysRoute
  SimulationsRoute: typeof SimulationsRoute
  SystemRoute: typeof SystemRoute
  UsageRoute: typeof UsageRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SettingsAccessRoute: typeof SettingsAccessRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replays': {
      id: '/replays'
      path: '/replays'
      fullPath: '/replays'
      preLoaderRoute: typeof ReplaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations': {
      id: '/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof SimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/access': {
      id: '/settings/access'
      path: '/settings/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof SettingsAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/settings/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecisionsRoute: DecisionsRoute,
  ModelsRoute: ModelsRoute,
  ReplaysRoute: ReplaysRoute,
  SimulationsRoute: SimulationsRoute,
  SystemRoute: SystemRoute,
  UsageRoute: UsageRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SettingsAccessRoute: SettingsAccessRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
