import { describe, expect, it } from "vitest";
import { decodeConnectRequest, decodeMapUploadRequest, decodeTickRequest } from "../src";
import connect from "./fixtures/arma-1.8.0.13/stavka-smoke-connect.json";
import initial from "./fixtures/arma-1.8.0.13/stavka-smoke-initial.json";
import full from "./fixtures/arma-1.8.0.13/stavka-smoke-full.json";
import delta from "./fixtures/arma-1.8.0.13/stavka-smoke-delta.json";
import removed from "./fixtures/arma-1.8.0.13/stavka-smoke-removed.json";
import terrain from "./fixtures/arma-1.8.0.13/stavka-smoke-map.json";
import contacts from "./fixtures/arma-1.8.0.13/stavka-smoke-contacts.json";

// Captured from the actual Workbench engine, not generated by the TypeScript
// serializer. These catch Enforce numeric-array, escaping and hash differences.
describe("Arma Reforger 1.8.0.13 native wire capture", () => {
  it("accepts the native connection identity", () => {
    expect(decodeConnectRequest(connect).mission_epoch).toBe(1);
  });

  it.each([initial, full, delta, contacts, removed])("accepts native tick $tick_id", (capture) => {
    expect(decodeTickRequest(capture).tick_id).toBe(capture.tick_id);
  });

  it("verifies the native terrain content hash", () => {
    const capture = decodeMapUploadRequest(terrain);
    expect(capture.briefing.source).toBe("arma_extracted");
    expect(capture.briefing.terrain_grid.length).toBeGreaterThan(0);
  });

  it("reports actual perception contacts after an empty initial enemy snapshot", () => {
    const initialCapture = decodeTickRequest(initial);
    const contactCapture = decodeTickRequest(contacts);
    if (initialCapture.type !== "full" || contactCapture.type !== "delta") {
      throw new Error("Expected initial full snapshot and contact delta");
    }
    expect(initialCapture.snapshot.known_enemies).toEqual([]);
    expect(contactCapture.changes.known_enemies_upserted.length).toBeGreaterThan(0);
    expect(contactCapture.changes.known_enemies_upserted[0]?.reported_by).toBe("g-smoke-spawn");
  });

  it("reports movement and deletion across acknowledged ticks", () => {
    const before = decodeTickRequest(full);
    const after = decodeTickRequest(delta);
    const end = decodeTickRequest(removed);
    if (before.type !== "full" || after.type !== "delta" || end.type !== "delta") {
      throw new Error("Expected full, delta, delta capture sequence");
    }
    expect(after.since_tick).toBe(before.tick_id);
    expect(after.changes.groups_upserted[0]?.position).not.toEqual(
      before.snapshot.friendly_groups[0]?.position,
    );
    expect(end.changes.groups_destroyed).toEqual(["g-smoke-spawn"]);
    expect(end.command_results).toContainEqual({
      command_id: "smoke-despawn",
      status: "completed",
    });
  });
});
