import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { Context, Effect, Layer } from "effect";

import { GatewayError } from "../domain/types";

const generatedMarker = "# Generated by maskirovka doctor";
const replaceablePlaceholders = new Set(["sk-stavka-replace-me"]);

export interface DevVarsSnapshot {
  readonly values: Readonly<Record<string, string>>;
  readonly explicitKeys: ReadonlySet<string>;
}

const parseValue = (value: string): string => {
  try {
    const parsed = JSON.parse(value) as unknown;
    return typeof parsed === "string" ? parsed : value;
  } catch {
    return value;
  }
};

const snapshotFrom = (content: string): DevVarsSnapshot => {
  const lines = content.split(/\r?\n/u);
  const markerIndex = lines.indexOf(generatedMarker);
  const explicitLines = markerIndex < 0 ? lines : lines.slice(0, markerIndex);
  const values: Record<string, string> = {};
  for (const line of lines) {
    const match = line.match(/^([A-Z0-9_]+)=(.*)$/u);
    if (match?.[1] !== undefined && match[2] !== undefined) {
      values[match[1]] = parseValue(match[2]);
    }
  }
  return {
    values,
    explicitKeys: new Set(explicitLines.flatMap((line) => {
      const match = line.match(/^([A-Z0-9_]+)=(.*)$/u);
      if (!match?.[1] || match[2] === undefined) return [];
      return replaceablePlaceholders.has(parseValue(match[2])) ? [] : [match[1]];
    })),
  };
};

export interface DevVarsRepositoryService {
  readonly read: (
    filename: string,
  ) => Effect.Effect<DevVarsSnapshot, GatewayError>;
  readonly write: (
    filename: string,
    values: Readonly<Record<string, string>>,
  ) => Effect.Effect<void, GatewayError>;
}

export class DevVarsRepository extends Context.Service<DevVarsRepository, DevVarsRepositoryService>()(
  "@stavka/maskirovka/DevVarsRepository",
) {}

export class FileDevVarsRepository implements DevVarsRepositoryService {
  read(filename: string): Effect.Effect<DevVarsSnapshot, GatewayError> {
    return Effect.tryPromise({
      try: async () => {
        try {
          return snapshotFrom(await readFile(filename, "utf8"));
        } catch (error) {
          if ((error as NodeJS.ErrnoException).code === "ENOENT") return snapshotFrom("");
          throw error;
        }
      },
      catch: (cause) => new GatewayError(
        500,
        "DEV_VARS_REPOSITORY_FAILURE",
        "Unable to read development variables",
        [cause instanceof Error ? cause.message : "Unknown .dev.vars error"],
      ),
    });
  }

  write(
    filename: string,
    values: Readonly<Record<string, string>>,
  ): Effect.Effect<void, GatewayError> {
    return Effect.tryPromise({
      try: async () => {
        let existing = "";
        try {
          existing = await readFile(filename, "utf8");
        } catch (error) {
          if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
        }
        const lines = existing.split(/\r?\n/u);
        const markerIndex = lines.indexOf(generatedMarker);
        const operatorLines = markerIndex < 0 ? lines : lines.slice(0, markerIndex);
        const explicitKeys = snapshotFrom(existing).explicitKeys;
        const kept = operatorLines
          .filter((line) => {
            const match = line.match(/^([A-Z0-9_]+)=(.*)$/u);
            return !match?.[1] ||
              !Object.hasOwn(values, match[1]) ||
              !replaceablePlaceholders.has(parseValue(match[2] ?? ""));
          })
          .filter((line, index, lines) =>
            line !== "" || (index > 0 && lines[index - 1] !== ""));
        const generated = Object.entries(values)
          .filter(([key]) => !explicitKeys.has(key))
          .map(([key, value]) => `${key}=${JSON.stringify(value)}`);
        const content = [...kept, generatedMarker, ...generated, ""].join("\n");
        await mkdir(dirname(filename), { recursive: true });
        const temporary = `${filename}.${process.pid}.${crypto.randomUUID()}.tmp`;
        await writeFile(temporary, content, { encoding: "utf8", mode: 0o600 });
        await rename(temporary, filename);
      },
      catch: (cause) => new GatewayError(
        500,
        "DEV_VARS_REPOSITORY_FAILURE",
        "Unable to write generated development variables",
        [cause instanceof Error ? cause.message : "Unknown .dev.vars error"],
      ),
    });
  }
}

export const DevVarsRepositoryLive: Layer.Layer<DevVarsRepository> =
  Layer.succeed(DevVarsRepository, new FileDevVarsRepository());
